export const SEARCH_DATA = [
    {
        id: '1',
        url: 'https://picsum.photos/300?1',
        username: 'maria_dev',
        caption: 'Enjoying a peaceful day at the beach.',
        hashtags: ['#beach', '#sun', '#relax'],
    },
    {
        id: '2',
        url: 'https://picsum.photos/300?2',
        username: 'travel_addict',
        caption: 'Mountains calling, and I must go!',
        hashtags: ['#mountains', '#travel', '#adventure'],
    },
    {
        id: '3',
        url: 'https://picsum.photos/300?3',
        username: 'foodielife',
        caption: 'Fresh pasta is always a good idea.',
        hashtags: ['#foodie', '#pasta', '#yum'],
    },
    {
        id: '4',
        url: 'https://picsum.photos/300?4',
        username: 'citywalker',
        caption: 'Night lights and quiet streets.',
        hashtags: ['#citylife', '#night', '#urban'],
    },
    {
        id: '5',
        url: 'https://picsum.photos/300?5',
        username: 'petlover',
        caption: 'Best friend forever.',
        hashtags: ['#pets', '#dog', '#cute'],
    },
    {
        id: '6',
        url: 'https://picsum.photos/300?6',
        username: 'sunsetdreams',
        caption: 'Chasing sunsets every day.',
        hashtags: ['#sunset', '#sky', '#dream'],
    },
    {
        id: '7',
        url: 'https://picsum.photos/300?7',
        username: 'fitness_girl',
        caption: 'Progress is progress.',
        hashtags: ['#fitness', '#gym', '#motivation'],
    },
    {
        id: '8',
        url: 'https://picsum.photos/300?8',
        username: 'techguy',
        caption: 'Building cool things with code.',
        hashtags: ['#tech', '#developer', '#coding'],
    },
    {
        id: '9',
        url: 'https://picsum.photos/300?9',
        username: 'naturelover',
        caption: 'Green everywhere 🌿',
        hashtags: ['#forest', '#nature', '#green'],
    },
    {
        id: '10',
        url: 'https://picsum.photos/300?10',
        username: 'artsyvibes',
        caption: 'Finding beauty in everyday moments.',
        hashtags: ['#art', '#aesthetic', '#creative'],
    },
    {
        id: '11',
        url: 'https://picsum.photos/300?11',
        username: 'wanderlust',
        caption: 'Take only memories, leave only footprints.',
        hashtags: ['#travel', '#wanderlust', '#explore'],
    },
    {
        id: '12',
        url: 'https://picsum.photos/300?12',
        username: 'coffeequeen',
        caption: 'Fueling creativity since morning.',
        hashtags: ['#coffee', '#latte', '#morningvibes'],
    },
    {
        id: '13',
        url: 'https://picsum.photos/300?13',
        username: 'oceanmind',
        caption: 'The ocean is my happy place.',
        hashtags: ['#ocean', '#waves', '#blue'],
    },
    {
        id: '14',
        url: 'https://picsum.photos/300?14',
        username: 'streetphotography',
        caption: 'Captured during my morning walk.',
        hashtags: ['#street', '#photography', '#life'],
    },
    {
        id: '15',
        url: 'https://picsum.photos/300?15',
        username: 'minimalism',
        caption: 'Less is more.',
        hashtags: ['#minimal', '#clean', '#simple'],
    },
];
